name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: snake-workflow
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%230EA5E9&color_dots=%23ebedf0,%23c6e48b,%237bc96f,%23239a3b,%23196127
            dist/github-snake-dark.svg?color_snake=%230EA5E9&color_dots=%23161b22,%230e4429,%23006d32,%2326a641,%2339d353

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
